### PR TITLE
Prevent hybrid and bm25 search from being used with sort

### LINKED ISSUE #2758: Add exception when sort combined with bm25/hybrid
We currently silently ignore sorting when combined with `bm25`/`hybrd`. We should return an exception for now, as we're rethinking the new implementation 

Will create new story later for the proper implementation

### PR DESCRIPTION
**Pull request by parkerduckworth**
### What's being changed:

Prevents hybrid and bm25 search from being used with sort. Once the team determines how we can support sort + these filters, the checks can be removed

Closes #2758

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

File: adapters/handlers/graphql/local/get/class_builder_fields.go [hunk 1]
```diff
@@ -372,6 +372,9 @@ func (r *resolver) makeResolveGetClass(className string) graphql.FieldResolveFn
 		// extracts bm25 (sparseSearch) from the query
 		var keywordRankingParams *searchparams.KeywordRanking
 		if bm25, ok := p.Args["bm25"]; ok {
+			if len(sort) > 0 {
+				return nil, fmt.Errorf("bm25 search is not compatible with sort")
+			}
```
Comment (antas-marcin) [inline adapters/handlers/graphql/local/get/class_builder_fields.go:377]: I think that all of our validation logic for GraphQL we place here in [explorer.GetClass](https://github.com/weaviate/weaviate/blob/master/usecases/traverser/explorer.go#L108-L139) method

File: adapters/repos/db/index.go [hunk 2]
```diff
@@ -1007,15 +1007,16 @@ func (i *Index) objectVectorSearch(ctx context.Context, searchVector []float32,
...
-	if len(shardNames) > 1 && len(sort) > 0 {
-		return i.sort(out, dists, sort, limit)
+	var err error
+	if len(sort) > 0 {
+		out, dists, err = i.sort(out, dists, sort, limit)
+		if err != nil {
+			i.logger.WithField("action", "sort_vector_search_results").Error(err.Error())
+		}
+	} else if len(shardNames) > 0 {
+		out, dists = newDistancesSorter().sort(out, dists)
```
Comment (antas-marcin) [inline adapters/repos/db/index.go:1017]: shouldn't this kick in only only when there's a multishard setup? now it runs every time

Comment (parkerduckworth) [reply adapters/repos/db/index.go]: This change has been reverted. The nearText sort already worked without this change

File: adapters/repos/db/index.go [hunk 3]
```diff
@@ -1007,15 +1007,16 @@ func (i *Index) objectVectorSearch(ctx context.Context, searchVector []float32,
...
 	}
 
-	if len(shardNames) == 1 {
-		return out, dists, nil
-	}
-
-	if len(shardNames) > 1 && len(sort) > 0 {
-		return i.sort(out, dists, sort, limit)
+	var err error
+	if len(sort) > 0 {
```
[the remark this answers is not in the document]
Comment (parkerduckworth) [reply adapters/repos/db/index.go]: Change reverted

File: adapters/handlers/graphql/local/get/class_builder_fields.go (hunk 1 above)
Comment (parkerduckworth) [reply adapters/handlers/graphql/local/get/class_builder_fields.go:377]: The benefit of having the checks here, is that the GQL query will fail to resolve with this incompatible set of parameters. If we move the checks to `(Explorer) GetClass`, then the query will resolve successfully, when it could have been determined ahead of resolution that query is invalid.

That being said, I don't think there is a huge practical difference during usage, so if you still want this change, I can do so

**Review by aliszka — APPROVED** [review]

**Comment by qedpi** [comment]
Hi weaviate team,

"Once the team determines how we can support sort + these filters, the checks can be removed"
Wondering if there have been any updates on this feature?

**Comment by kranthi419** [comment]
Hi weaviate team and @dudanogueira ,
any update on this?
