### PR TITLE
Fix parsing of ContainsAny / All operator array values in cluster environment

### LINKED ISSUE #3559: ContainsAny operator returns error
If I run this query on Weaviate version `1.21.3`:
```graphql
{
  Get {
    MyClass(
      nearText: {concepts: ["some concept"]}
      where: {
        path: ["path"],
        valueText: ["SomeValue"],
        operator: ContainsAny
      }
    ){
      _additional {
        distance
      }
    }
  }
}
```
It runs and returns this error after around 7 seconds:

```json
{
  "data": {
    "Get": {
      "MyClass": null
    }
  },
  "errors": [
    {
      "locations": [
        {
          "column": 5,
          "line": 3
        }
      ],
      "message": "explorer: get class: vector search: object vector search at index grant: remote shard aqkmTCSWwqmw: status code: 500, error: shard grant_aqkmTCSWwqmw: build inverted filter allow list: value type should be []string but is []interface {}\n: context deadline exceeded",
      "path": [
        "Get",
        "MyClass"
      ]
    }
  ]
}
```

If I run it with `Equal` operator it works:
```graphql
{
  Get {
    MyClass(
      nearText: {concepts: ["some concept"]}
      where: {
        path: ["path"],
        valueText: "SomeValue",
        operator: Equal
      }
    ){
      _additional {
        distance
      }
    }
  }
}
```

Seems like a bug in `ContainsAny`.

### PR DESCRIPTION
**Pull request by antas-marcin**
### What's being changed:

This PR resolves #3559

When Weaviate is configured in cluster setup then a search request (with given filters) is being serialized and sent out to all nodes in cluster to get find the results. After the search request deserialization (in cluster API) into an object all of the array types are unmarshalled using `[]interface{}` type and the `searcher` logic didn't take that into account.

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

File: test/acceptance_with_go_client/filters_tests/where_test.go [hunk 1]
```diff
@@ -466,3 +468,22 @@ func TestWhereFilter(t *testing.T) {
 		}
 	})
 }
+
+func TestWhereFilter_Cluster(t *testing.T) {
```
Comment (parkerduckworth) [inline test/acceptance_with_go_client/filters_tests/where_test.go:472]: ❤️

**Review by parkerduckworth — APPROVED** [review]
