### PR TITLE
Fix PQ recall drop after restart

### LINKED ISSUE #3049: Bug: PQ recall not identical after restart
(will add more content as I find out more)

### PR DESCRIPTION
**Pull request by etiennedi**
Please review & merge #3050 first because this PR builds on top of it.

### What's being changed:
* fixes #3049 
* the cursor used to prefill the compressed cache reuses its memory internally. However, we assigned this memory straight to the cache. This means we could end up with all identical vectors in the cache after a restart.
* This fix copies the memory before calling `.Next()` to make sure the memory is unique.
* This was discovered as part of building a new e2e pipeline containing a restart. This new pipeline will act as the test that prevents a regression.

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [x] Chaos pipeline run or not necessary. Link to pipeline: https://github.com/weaviate/weaviate-chaos-engineering/actions/runs/5037759071/jobs/9034798226
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

File: adapters/repos/db/vector/hnsw/condensor_integration_test.go [hunk 1]
```diff
@@ -487,6 +488,68 @@ func TestCondensorWithoutEntrypoint(t *testing.T) {
...
+	logger, _ := test.NewNullLogger()
+	uncondensed, err := NewCommitLogger(rootPath, "uncondensed", logger,
+		WithCommitlogCycleTicker(cyclemanager.NewNoopTicker))
+	require.Nil(t, err)
+	defer uncondensed.Shutdown(ctx)
+
+	t.Run("add pq info", func(t *testing.T) {
+		uncondensed.AddPQ(ssdhelpers.PQData{
+			Ks:                  3,
+			M:                   0,
```
Comment (trengrj) [inline adapters/repos/db/vector/hnsw/condensor_integration_test.go:505]: Maybe safer here to set `M` to something non-zero? It should always be a positive number that divides the dimensions.

Comment (trengrj) [reply adapters/repos/db/vector/hnsw/condensor_integration_test.go:505]: Ah reading your reasoning in #3050

**Review by abdelr — APPROVED** [review]
