### PR TITLE
fix: provide a better error message when configuration for named vector does not exist

### LINKED ISSUE #151: Release Swagger version v0.5.3
Release version https://github.com/weaviate/weaviate-swagger/releases/tag/v0.5.3

### PR DESCRIPTION
**Pull request by faustuzas**
### What's being changed:

Fixes #151

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

File: test/acceptance_with_go_client/named_vectors_tests/test_suits/named_vectors_objects_mixed.go [hunk 1]
```diff
@@ -209,6 +212,54 @@ func testCreateSchemaWithMixedVectorizers(host string) func(t *testing.T) {
...
+					}).
+					WithVectors(models.Vectors{
+						"non_existent_vector": []float32{0.1, 0.2, 0.3},
+					}).
+					Do(ctx)
+				require.Error(t, err)
+				var clientError *fault.WeaviateClientError
+				require.True(t, errors.As(err, &clientError))
+				require.Equal(t, 422, clientError.StatusCode)
+				require.Contains(t, clientError.Msg, fmt.Sprintf("collection %s does not have configuration for vector non_existent_vector", className))
```
Comment (bevzzz) [inline test/acceptance_with_go_client/named_vectors_tests/test_suits/named_vectors_objects_mixed.go:231]: perfect timing with the PR -- we've just ran into this same issue with @g-despot and agreed that the error message could've been better
