### PR TITLE
fix db delete tenant to also delete inactive tenant

### LINKED ISSUE #8889: Deleting an inactive tenant leaves the folder in the disk
### How to reproduce this bug?

When a tenant is in INACTIVE/COLD state and we issue a delete tenant request, the tenant will be removed from the schema, but the tenant folder will remain in the /var/lib/weaviate/<collection> folder.

This could then enter in conflict if the same tenant gets recreated later, using the objects from the already deleted tenant.

To reproduce this issue I used [weaviate-local-k8s](https://github.com/weaviate/weaviate-local-k8s) and [weaviate-cli](https://github.com/weaviate/weaviate-cli), but it could be easily reproduced with docker and a python script.

- Create a single instance
```
WEAVIATE_VERSION="1.32.0"  REPLICAS=1 WORKERS=1 ./local-k8s.sh setup
```
- Create a collection with multi-tenancy enabled:
```
weaviate-cli create collection --replication_factor 3 --multitenant --replication_factor 1
Collection 'Movies' created successfully in Weaviate.
```

- Create two tenants for that collection
```
weaviate-cli create tenants --number_tenants 2
2 tenants added with tenant status 'TenantActivityStatus.ACTIVE' for collection 'Movies'
```
- Add some data for each of the tenants
```
weaviate-cli create data --limit 10
Preparing to insert 10 objects into class 'Movies'
Processing objects for tenant 'Tenant-1'
Importing 10 objects from Movies dataset
Finished processing 10 objects.
Inserted 10 objects into class 'Movies'
Processing objects for tenant 'Tenant-0'
Importing 10 objects from Movies dataset
Finished processing 10 objects.
Inserted 10 objects into class 'Movies'
```

- Update 1 of the 2 tenants into inactive state:
```
weaviate-cli update tenants --number_tenants 1 --state inactive
1 tenants updated with tenant status 'TenantActivityStatus.INACTIVE' for class 'Movies'.
```
- Check for their state:
```
weaviate-cli get tenants --verbose

Tenant Name                   Activity Status     
Tenant-1                      INACTIVE            
Tenant-0                      ACTIVE   
```

- We verify that the folder is present for both tenants:
```
kubectl exec -it weaviate-0 -n weaviate -- sh -c "ls -l /var/lib/weaviate/movies/"
Defaulted container "weaviate" out of: weaviate, configure-sysctl (init)
total 8
drwxr-xr-x    5 root     root          4096 Aug 12 10:10 Tenant-0
drwxr-xr-x    5 root     root          4096 Aug 12 10:11 Tenant-1
```

- Delete the 2 tenants from the collection:
```
weaviate-cli delete tenants --number_tenants 2
2 tenants deleted
```
- Now, we go an check how many tenants there are in the system, no tenants are present:
```
weaviate-cli get tenants 
Number Tenants      Cold Tenants        Hot Tenants         Offloaded Tenants   
0                   0                   0                   0                   
```
- But when checking the content in the pod's disks, the tenant folder for the cold tenant is still there:
```
kubectl exec -it weaviate-0 -n weaviate -- sh -c "ls -l /var/lib/weaviate/movies/"
Defaulted container "weaviate" out of: weaviate, configure-sysctl (init)
total 4
drwxr-xr-x    5 root     root          4096 Aug 12 10:11 Tenant-1
```
- If I now re-create the two tenants, `Tenant-1` will have all of a sudden 10 objects, even though I haven't added any data:
```
weaviate-cli create tenants --number_tenants 2
2 tenants added with tenant status 'TenantActivityStatus.ACTIVE' for collection 'Movies'
weaviate-cli get collection

Collections:
+------------+--------------+---------+---------+--------------+--------------+---------------+------------+
| Collection | Multitenancy | Tenants | Objects | Repl. Factor | Vector Index | Named Vectors | Vectorizer |
+------------+--------------+---------+---------+--------------+--------------+---------------+------------+
| Movies     | True         | 2       | 10      | 1            | hnsw         | False         | none       |
+------------+--------------+---------+---------+--------------+--------------+---------------+------------+

Total: 1 collections
```

### What is the expected behavior?

The inactive tenant should also get deleted 

### What is the actual behavior?

Inactive tenants does not disapear from the disk, taking space in the cluster and also leaving the cluster in some inconsistent state, with data which was expected to be removed still present.
Thinking about this, it can even be considered as a security concern, as if by any chance a tenant for another user gets recreated with the same name, all of a sudden the data from the deleted on cold tenant will be available right away upon creation.

### Supporting information

This issue seems to be present also in old versions, it was reproduced in 1.28.16.
It occurs with one ore three nodes.

### Server Version

1.25.0 up to 1.32.0

### Weaviate Setup

Single Node

### Nodes count

1 or 3

### Code of Conduct

- [x] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

### PR DESCRIPTION
**Pull request by reyreaud-l**
### What's being changed:

When a tenant is deleted the data on disk is only deleted if the tenant is active at the moment of the deletion. This change ensures that the data deletion happens regardless of the tenant status.

Fixes #8889 

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

File: adapters/repos/db/index.go [hunk 1]
```diff
@@ -2332,13 +2332,18 @@ func (i *Index) dropShards(names []string) error {
...
-				return nil // shard already does not exist (or inactive)
-			}
-
-			if err := shard.drop(); err != nil {
-				ec.Add(err)
-				i.logger.WithField("action", "drop_shard").
-					WithField("shard", shard.ID()).Error(err)
+				// Ensure that if the shard is not loaded we delete any reference on disk for any data.
+				// This ensures that we also delete inactive shards/tenants
+				if err := os.RemoveAll(shardPath(i.path(), name)); err != nil {
```
Comment (reyreaud-l) [inline adapters/repos/db/index.go:2337]: Note that I took that line from shard_lazyloader.go drop routine that avoids loading the shard to drop is aswell

**Review by moogacs — APPROVED** [review]

**Comment by jfrancoa** [comment]
Tested with good results, the folder is now gone once the inactive tenant gets deleted
