### PR TITLE
Make sure shard is properly cleaned up on partial load

### LINKED ISSUE #5100: Re-loading a shard that failed to load initially can corrupt data (Lazy shard loading)
### How to reproduce this bug?

This one is a bit tricky to reproduce, but not impossible:

- Import in a way that you get many small segments that aren't compacted or otherwise stop a Weaviate process so that the object store has compactions left
- Shutdown the server
- Corrupt a property (for example, by creating a zero-length segment file or manually messing up an existing segment file)
- Restart Weaviate and wait for shard loading to fail because of the property corrupted in the previous step
- Send (many) query requests that require this shard

### What is the expected behavior?

Loading of a shard is atomic, it's either loaded or not. Since one of the shard's buckets is corrupt in this case, we would expect that the entire shard cannot be loaded.

### What is the actual behavior?

The bucket is partially loaded. All buckets loaded prior to finding the corrupt bucket are actually running. However, the next attempt to initialize the shard again is no longer idempotent. A bucket could be initialized multiple times. This also means that multiple processes might try to run compactions on the same file in parallel.

This is highly dangerous, it can corrupt existing files on disk, as well as lead to crashes, such as this one:

```
unexpected fault address 0x3491e4010
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x3491e4010 pc=0x102ce6af8]

goroutine 20780 [running]:
runtime.throw({0x103ce570b?, 0x0?})
        /usr/local/go/src/runtime/panic.go:1077 +0x40 fp=0x140000c6670 sp=0x140000c6640 pc=0x102caea90
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:875 +0x22c fp=0x140000c66d0 sp=0x140000c6670 pc=0x102cc693c
runtime.memmove()
        /usr/local/go/src/runtime/memmove_arm64.s:57 +0x48 fp=0x140000c66e0 sp=0x140000c66e0 pc=0x102ce6af8
bytes.(*Reader).Read(0x1400326ac30, {0x14002e97100?, 0x140000c6798?, 0x105850108?})
        /usr/local/go/src/bytes/reader.go:44 +0x84 fp=0x140000c6710 sp=0x140000c66e0 pc=0x102d8a5c4
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*nodeReader).Read(0x14002e97100?, {0x14002e97100?, 0x140000c6788?, 0x10347ab30?})
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment.go:233 +0x2c fp=0x140000c6740 sp=0x140000c6710 pc=0x10346d9dc
io.ReadAtLeast({0x104625ca0, 0x14002d985a0}, {0x14002e97100, 0x9, 0x9}, 0x9)
        /usr/local/go/src/io/io.go:335 +0xa0 fp=0x140000c6790 sp=0x140000c6740 pc=0x102d2cde0
io.ReadFull(...)
        /usr/local/go/src/io/io.go:354
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.ParseReplaceNode({0x104625ca0, 0x14002d985a0}, 0x1)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_serialization.go:112 +0x90 fp=0x140000c68b0 sp=0x140000c6790 pc=0x10347ab50
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*segmentCursorReplace).parseReplaceNode(0x140066d27c0, {0x1400495c510?, 0x10?})
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/cursor_segment_replace.go:135 +0x68 fp=0x140000c6a00 sp=0x140000c68b0 pc=0x1034649e8
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*segmentCursorReplace).firstWithAllKeys(0x140066d27c0)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/cursor_segment_replace.go:118 +0x54 fp=0x140000c6b50 sp=0x140000c6a00 pc=0x103464844
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*compactorReplace).writeKeys(0x140000c75b0)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/compactor_replace.go:104 +0x30 fp=0x140000c70f0 sp=0x140000c6b50 pc=0x10345a500
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*compactorReplace).do(0x140000c75b0)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/compactor_replace.go:65 +0x68 fp=0x140000c7150 sp=0x140000c70f0 pc=0x10345a288
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*SegmentGroup).compactOnce(0x14004b786c0)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_group_compaction.go:192 +0x4fc fp=0x140000c7750 sp=0x140000c7150 pc=0x103474e9c
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*SegmentGroup).compactIfLevelsMatch(0x14004b786c0, 0x102dca7c4?)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_group_compaction.go:377 +0x30 fp=0x140000c7bc0 sp=0x140000c7750 pc=0x103476f80
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*SegmentGroup).compactIfLevelsMatch-fm(0x49a50e92bf01?)
        <autogenerated>:1 +0x30 fp=0x140000c7be0 sp=0x140000c7bc0 pc=0x103483160
github.com/weaviate/weaviate/entities/cyclemanager.(*cycleCallbackGroup).cycleCallbackSequential.func1(0x14005205440, 0x14007223ce0, 0x14000000000?, 0x140066d61c0, 0x140000c7c87)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/entities/cyclemanager/cyclecallbackgroup.go:141 +0xd8 fp=0x140000c7c40 sp=0x140000c7be0 pc=0x103442558
github.com/weaviate/weaviate/entities/cyclemanager.(*cycleCallbackGroup).cycleCallbackSequential(0x14005205440, 0x140066d61c0)
```

### Supporting information

_No response_

### Server Version

Observed on `v1.24.x`. Should affect all versions with lazy shard loading

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

### PR DESCRIPTION
**Pull request by etiennedi**
Fixes #5100 

With lazy shard loading, you could get into a situation where a shard was only partially initialized if loading a bucket failed. On the next query, we would try to initialize it again. Unfortunately, that led to some buckets being initialized twice. This also means we had competing threads trying to run compactions on the same files, thus corrupting data.

This PR fixes this by making sure shard loading is atomic: Either a shard is fully loaded, or not. If loading fails, everything already loaded to that point is stopped again. For this, it makes the `(*Shard).Shutdown()` method idempotent, it simply skips stuff that hasn't been loaded yet. Without this change it would block forever. 

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

File: adapters/repos/db/shard_dimension_tracking.go [hunk 1]
```diff
@@ -126,6 +126,10 @@ func (s *Shard) initDimensionTracking() {
 		// leak. The actual work should be much faster.
 		ctx, cancel := context.WithTimeout(rootCtx, 30*time.Minute)
 		defer cancel()
+		defer func() {
+			s.dimensionTrackingInitialized.Store(true)
```
Comment (jeroiraz) [inline adapters/repos/db/shard_dimension_tracking.go:130]: might just be better to be at the beginning (without deferring it), otherwise if there is a quit shutdown before ending this function (rare but still) could do a leak of publishing routine

Comment (etiennedi) [reply adapters/repos/db/shard_dimension_tracking.go:130]: Good point, I'll move it.
