### PR TITLE
Fix a goroutine leak when deleting a class

### LINKED ISSUE #3536: Frequent creation and deletion of schemas and objects leads to degraded performance
I was running a test where every minute a new schema is created, a new object is added, the object is updated, the object is deleted and then the schema is deleted. Over a period of approx. 2 days this leads to increasing response times (> 10sec).

When investigating this issue, the pods was at 100% CPU load. Most CPU was consumed by a component called CycleManager. When restarting the Pod, performance was back to normal. (see screenshot)

Assumption is that there is a bug in cleaning up the processes that have been handling old schemas that meanwhile are deleted. 

image

### PR DESCRIPTION
**Pull request by etiennedi**
### What's being changed:
* fixes #3536 
* [Failing Chaos Pipeline](https://github.com/weaviate/weaviate-chaos-engineering/actions/runs/6763141537/job/18379912748?pr=150) using v1.22.2 as a control
* [Passing Chaos Pipeline](https://github.com/weaviate/weaviate-chaos-engineering/actions/runs/6763422408/job/18380525558) with an image from this branch 

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [x] Chaos pipeline run or not necessary. Link to pipeline: see ⬆️ 
- [x] All new code is covered by tests where it is reasonable: brand new chaos pipeline
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

File: adapters/repos/db/index.go [hunk 1]
```diff
@@ -1564,7 +1564,29 @@ func (i *Index) drop() error {
...
+	if err := eg.Wait(); err != nil {
+		return err
+	}
+
+	// Dropping the shards only unregisters the shards callbacks, but we still
+	// need to stop the cycle managers that those shards used to register with.
+	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
+	defer cancel()
+
+	if err := i.cycleCallbacks.compactionCycle.StopAndWait(ctx); err != nil {
```
Comment (reyreaud-l) [inline adapters/repos/db/index.go:1576]: Nitpick: could we make the cycleCallbacks struct provide a `StopAllCallbacksAndWait` function ? Would be handy in other places where we want to stop all stuff (also if/when we add a new callback).

Comment (aliszka) [reply adapters/repos/db/index.go]: done

**Review by aliszka — APPROVED** [review]
