### PR TITLE
Gracefully handle potential panics in batch add

### LINKED ISSUE #3440: [Bug]: No panic recovery in DB.Worker - A panic during a batch import can crash the whole setup
Example stack trace
```
panic: class AFEfbIdHcJbbBGCJIBcAGAIAaEFFAFcCd: shard k0DD71Ycaq26: findNewLocalEntrypoint called on an empty hnsw graph

goroutine 226 [running]:
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).findNewLocalEntrypoint(0xc246ef03c0, {0x1c1f240, 0xc54a958758}, 0x0, 0x0)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:538 +0x32d
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).pickEntrypoint(0xc1fbd0bb38)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:277 +0xfb
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).doAtLevel(0xc1fbd0bb38, 0x7ba339621108?)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:73 +0x65
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).Do(0xc1fbd0bb38)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:62 +0x52
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).findAndConnectNeighbors(0x26a0bc0?, 0x600?, 0xc62e44c000?, {0xc62e44c000?, 0x600?, 0x0?}, 0x0?, 0x7b94806a6bc0?, {0x1c1f240, 0xc54a958750})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:30 +0x99
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).insert(0xc246ef03c0, 0xc320029900, {0xc62e44c000, 0x600, 0x600})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/insert.go:190 +0x785
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).Add(0xc246ef03c0, 0x87, {0xc2baae3300, 0x600, 0x63f})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/insert.go:64 +0x290
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).updateVectorIndexIgnoreDelete(0xc004027860?, {0xc2baae3300?, 0xc8becb4650?, 0xc0040279a8?}, {0xc86f687ee0?, 0x47?, 0xc86f687ee0?})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_write_put.go:91 +0x51
github.com/weaviate/weaviate/adapters/repos/db.(*objectsBatcher).storeSingleObjectInAdditionalStorage(0xc83e86ad80, {0x1c16398?, 0xc6d54bbcb0?}, 0xc3e4c136c0, {0x0?, 0x0?, 0x0?}, 0x0?)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_write_batch_objects.go:276 +0x95
github.com/weaviate/weaviate/adapters/repos/db.(*DB).worker(0xc0038cc000)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/repo.go:227 +0x8e
created by github.com/weaviate/weaviate/adapters/repos/db.New
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/repo.go:118 +0x5ce
```

Notes to implementer:
- Make sure the fix applies to both HTTP/gRPC
- Make sure the ongoing async importing also reflects those

### PR DESCRIPTION
**Pull request by etiennedi**
### What's being changed:

Fixes #3440.

In the rare case that an unexpected panic occurs when trying to add a batch, it should not crash the whole system. Instead, Weaviate should gracefully recover. This new change does so by:

* putting the panic message into a user-facing error wrapped with a message about an unexpected error having occurred
* still printing the panic message and stack trace to the console as if the panic was uncaught, so that it can still be used for troubleshooting

This required adding the recover in two places because any time we spawn a new goroutine, an existing recovery (such as the global one in the HTTP middleware) no longer catches the panic. The current code spawns goroutines in two places:
- while iterating over indexes/shards there is a waitgroup that each spawns a new routine
- while working on vector indexing from the queue, each worker is a a separate goroutine

Tested manually, as there is no (known) way to invoke a panic through public interfaces. 

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

File: adapters/repos/db/index.go [hunk 1]
```diff
@@ -566,6 +567,17 @@ func (i *Index) putObjectBatch(ctx context.Context, objects []*storobj.Object,
...
 		go func(shardName string, group objsAndPos) {
 			defer wg.Done()
+
+			defer func() {
+				err := recover()
+				if err != nil {
+					for pos := range group.pos {
+						out[pos] = fmt.Errorf("an unexpected error occurred: %s", err)
+					}
+					fmt.Printf("panic: %s\n", err)
```
Comment (parkerduckworth) [inline adapters/repos/db/index.go:577]: Not sure if it matters, but I noticed that the go stdlib tends to write to stderr rather than stdout in this case:
```go
fmt.Fprintf(os.Stderr, "panic: %s\n", err)
```

**Review by parkerduckworth — APPROVED** [review]

File: adapters/repos/db/index.go (hunk 1 above)
Comment (etiennedi) [reply adapters/repos/db/index.go]: Great point. Adjusted both.

**Review by dirkkul — APPROVED** [review]
