### PR TITLE
Fix panics during highly concurrent tombstone cleanup

### LINKED ISSUE #4410: panic `findNewLocalEntrypoint called on an empty hnsw graph` with deletion concurrency > 1
### How to reproduce this bug?

1. Start Server with `TOMBSTONE_DELETION_CONCURRENCY=100`
2. Run the script below

```python3
import weaviate
import weaviate.classes as wvc
import numpy as np
import time

client = weaviate.connect_to_local()
client.collections.delete_all()

col = client.collections.create(
    "MyCol",
    vector_index_config=wvc.config.Configure.VectorIndex.hnsw(
        cleanup_interval_seconds=60
    ),
)

# col = client.collections.get("MyCol")

start = time.time()
with col.batch.fixed_size(100, 10) as batch:
    for j in range(50_000):
        batch.add_object(
            {"always_true": True, "i": j},
            vector=np.random.rand(1, 1536)[0].tolist(),
        )
took = time.time() - start
print(f"batch imported in {took:.2f}s")

while True:
    try:
        start = time.time()
        res = col.data.delete_many(
            where=wvc.query.Filter.by_property("i").greater_than(10)
        )
        took = time.time() - start
        print(f"batch deleted in {took:.2f}s")
        if res.matches == 0:
            break
    except Exception as e:
        print(e)
```

### What is the expected behavior?

No panic or crash

### What is the actual behavior?

```
panic: class MyCol: shard N4l1r6BcL6ww: findNewLocalEntrypoint called on an empty hnsw graph

goroutine 179345 [running]:
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).findNewLocalEntrypoint(0x140027c6000, {0x1024f4a40, 0x140101ef358}, 0x0, 0x2)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:608 +0x35c
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).pickEntrypoint(0x14038fddca8)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:416 +0xe0
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).doAtLevel(0x14038fddca8, 0x0)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:206 +0x9d8
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).Do(0x14038fddca8)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:81 +0x4c
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reconnectNeighboursOf(0x140027c6000?, 0x1024e9858?, 0x0?, {0x1401aac5800?, 0x1401aac5800?, 0x600?}, {0x0?, 0x0?}, 0x0?, 0x2?, ...)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:43 +0x9c
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighbor(0x140027c6000, 0x13, {0x1024f4a40, 0x140101ef350}, 0x1401f82cdd8?)
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:446 +0x770
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighborsOf.func1()
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:332 +0x134
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/vendor/golang.org/x/sync/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 179339
        /Users/etiennedilocker/code/github.com/weaviate/weaviate/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0x98
exit status 2

```

### Supporting information

- Concurrent delete cleanup was newly introduced in `v1.24`
- It seems this issue can be mitigated by explicitly setting `TOMBSTONE_DELETION_CONCURRENCY=1` which leads to similar behavior as `v1.23`

### Server Version

`v1.24.1` - seems to have been newly added with v1.24

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

### PR DESCRIPTION
**Pull request by abdelr**
### What's being changed:
If the entry point is marked as deleted and we have a high concurrency level for the tombstones cleanup the server panics.

fixes #4410

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [X] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

File: adapters/repos/db/vector/hnsw/delete.go [hunk 1]
```diff
@@ -243,6 +243,7 @@ func (h *hnsw) cleanUpTombstonedNodes(shouldAbort cyclemanager.ShouldAbortCallba
 	} else if !ok {
 		return executed, nil
 	}
+	h.reassignNeighbor(h.entryPointID, deleteList, breakCleanUpTombstonedNodes)
```
Comment (trengrj) [inline adapters/repos/db/vector/hnsw/delete.go:246]: Shouldn't this use `h.getEntryPoint()` instead of `h.entryPointID`?

**Comment by rthiiyer82** [comment]
```2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9d07e8]
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | 
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | goroutine 994700 [running]:
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).searchLayerByVectorWithDistancer(0x4002236c80, {0x403898c700, 0x20, 0x20}, 0x0?, 0x1, 0x2, {0x0?, 0x0?}, {0x0, ...})
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/search.go:271 +0x7c8
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).findBestEntrypointForNode(0x4002236c80, 0x18a6b70?, 0x0, 0x403ba69980?, {0x403898c700, 0x20, 0x20}, {0x0?, 0x0?})
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/index.go:431 +0x1d8
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighbor(0x4002236c80, 0xa562, {0x18b2480, 0x4002a0e880}, 0x73616c43223a2273?)
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:409 +0x41c
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighborsOf.func1()
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:334 +0x144
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | golang.org/x/sync/errgroup.(*Group).Go.func1()
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x58
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 994218
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x98
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | panic: runtime error: invalid memory address or nil pointer dereference
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9d07e8]
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | 
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | goroutine 994829 [running]:
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).searchLayerByVectorWithDistancer(0x4002236c80, {0x4010790900, 0x20, 0x20}, 0x0?, 0x1, 0x2, {0x0?, 0x0?}, {0x0, ...})
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/search.go:271 +0x7c8
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).findBestEntrypointForNode(0x4002236c80, 0x18a6b70?, 0x0, 0x404e871400?, {0x4010790900, 0x20, 0x20}, {0x0?, 0x0?})
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/index.go:431 +0x1d8
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighbor(0x4002236c80, 0xa473, {0x18b2480, 0x4002a0e880}, 0x31353631332e302c?)
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:409 +0x41c
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighborsOf.func1()
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:334 +0x144
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  | golang.org/x/sync/errgroup.(*Group).Go.func1()
2024-03-07 11:30:34 weaviate-weaviate-node-1-1  |       /go/pkg/mod/golang.org/x/sync@v0.6.0/errgr

Above Panic observed in the pr branch.

**Review by asdine — APPROVED** [review]

**Review by antas-marcin — APPROVED** [review]
