### PR TITLE
gh-2662 add property module config fix

### LINKED ISSUE #2662: moduleConfig not taken into account when adding property
When you [add a property](https://weaviate.io/developers/weaviate/api/rest/schema#add-a-property) via `POST v1/schema/{class_name}/properties`, the `moduleConfig` parameter is not being taken into account.

Steps to reproduce:

1. Download Weaviate's docker image.

```sh
curl -o docker-compose.yml "https://configuration.weaviate.io/v2/docker-compose/docker-compose.yml?contextionary_compound_splitting=false&contextionary_language=en&contextionary_model=0.16.0&generative_openai=false&gpu_support=false&media_type=text&modules=modules&ner_module=true&ner_module_model=dbmdz-bert-large-cased-finetuned-conll03-english&qna_module=true&qna_module_model=distilbert-base-uncased-distilled-squad&ref2vec_centroid=false&runtime=docker-compose&spellcheck_module=false&sum_module=false&text_module=text2vec-contextionary&weaviate_version=v1.17.4"
```

2. Run it.

```sh
docker-compose up -d
```

3. Create an example class.

```sh
curl \
-X POST \
-H "Content-Type: application/json" \
-d '{
    "class": "Article",
    "description": "A written text, for example a news article or blog post",
    "properties": [
        {
        "dataType": [
            "string"
        ],
        "description": "Title of the article",
        "name": "title"
        },
        {
        "dataType": [
            "text"
        ],
        "description": "The content of the article",
        "name": "content"
        }
    ]
}' \
http://localhost:8080/v1/schema
```

4. Create a property with the `moduleConfig` setting.

```sh
curl \
-X POST \
-H "Content-Type: application/json" \
-d '{
    "dataType": [
      "boolean"
    ],
    "name": "onHomepage",
    "moduleConfig": {
      "text2vec-contextionary": {
        "skip": true
      }
    }
}' \
http://localhost:8080/v1/schema/Article/properties
```

The result is `skip` being `false`.

```
{"dataType":["boolean"],"moduleConfig":{"text2vec-contextionary":{"skip":false,"vectorizePropertyName":false}},"name":"onHomepage"}
```

### PR DESCRIPTION
**Pull request by shreyanshshah27**
### Review checklist

- [x] Chaos pipeline run or not necessary. Link to pipeline:
- [x] All new code is covered by tests where it is reasonable.
- [x] Performance tests have been run or not necessary.

### CODE REVIEW

File: usecases/modules/module_config_init_and_validate_test.go [hunk 1]
```diff
@@ -216,6 +216,57 @@ func TestValidateClass(t *testing.T) {
 	})
 }
 
+func TestSetSinglePropertyDefaults(t *testing.T) {
+	t.Run("add property after creating the class", func(t *testing.T) {
```
Comment (dirkkul) [inline usecases/modules/module_config_init_and_validate_test.go:220]: I think we do not need the t.run here. That is mainly used when you have multiple sub_tests that should run independently.

File: usecases/modules/module_config_init_and_validate.go [hunk 2]
```diff
@@ -88,18 +86,21 @@ func (p *Provider) setPerPropertyConfigDefaults(class *models.Class,
...
 ) {
 	dt, _ := schema.GetValueDataTypeFromString(prop.DataType[0])
 	modDefaults := cc.PropertyConfigDefaults(dt)
-	userSpecified := cfg.Property(prop.Name)
 	mergedConfig := map[string]interface{}{}
+	userSpecified := make(map[string]interface{})
+
+	if prop.ModuleConfig != nil {
+		userSpecified = prop.ModuleConfig.(map[string]interface{})[class.Vectorizer].(map[string]interface{})
+	}
```
Comment (dirkkul) [inline usecases/modules/module_config_init_and_validate.go:103]: Quick question, so I'm getting it right.

Before we were calling cfg.Property(prop.Name), which would check for the property in the schema. This does not exist yet and therefore returns an empty map. This causes the user provided configs to be ignored?

**Comment by shreyanshshah27** [comment]
> To avoid any confusion in the future about your contribution to Weaviate, we work with a [Contributor License Agreement](https://www.semi.technology/playbooks/misc/contributor-license-agreement.html). If you agree, you can simply add a comment to this PR that you agree with the CLA so that we can merge.beep boop - the SeMI bot waverobotPS:Are you already a member of the [Weaviate Slack channel?](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw)

I agree with the Contributor License Agreement.

File: usecases/modules/module_config_init_and_validate_test.go (hunk 1 above)
Comment (shreyanshshah27) [reply usecases/modules/module_config_init_and_validate_test.go]: Makes sense. Fixed.

File: usecases/modules/module_config_init_and_validate.go (hunk 2 above)
Comment (shreyanshshah27) [reply usecases/modules/module_config_init_and_validate.go:103]: Yes that's correct. Earlier we were using `cfg.Property(prop.Name)` to get the `ModuleConfig` from the new property that the user is trying to add. But since this is a new property that the user is trying to add, so it isn't actually present in the list of `class.Properties` and that's why, for the new property it will always return empty map.

Comment (dirkkul) [reply usecases/modules/module_config_init_and_validate.go:103]: great, than your fix is good :)

One thing I'd change is that you assume that your type castings work and that the vectorizer is part of the update which might both not be the case.

The problem is that we currently do not return errors to the caller. So I think we need to change that, eg add an error as the return value of the function and pass it up the stack until we reach addClassProperty.  

And then we can properly return any errors in the update (I'm sure the errors and variable names can be made nicer, just wanted to a quick POC):

```
modconfig, ok := prop.ModuleConfig.(map[string]interface{})
if !ok{
   return error.New("Wrong type")
}
vectorizerConfig, ok := modconfig[class.Vectorizer]
if !ok{
   return error.New("Vectorizer module not part of property update")
}
vectorizerConfigMap, ok := vectorizerConfig.(map[string]interface{})
if !ok{
   return error.New("Wrong type")
}
}
```

and then one test to make sure that we get an error if a wrong moduleName is passed in and then we are ready to merge :)

Comment (shreyanshshah27) [reply usecases/modules/module_config_init_and_validate.go:119]: As you suggested, I tried to add this. But this is what I found : 

Earlier we were using `cfg.Property(prop.Name)`, Now this function used to do very similar thing to what you suggested, i.e. check for all the errors but if any error found, then just return the empty config i.e. return `map[string]interface{}{}`. 

Now, according to me what you suggested should be the ideal behavior i.e. have a check for all these conditions, and return error accordingly and the error should fall in some bad request category. But it will change the entire current behavior. 

So we can have a check for all these conditions, and after that either we can return error or if any condition is violated just use some empty data-structure.

Let me know how do you want to proceed ahead?

Comment (dirkkul) [reply usecases/modules/module_config_init_and_validate.go:119]: I see your point. I'm not a fan of the idea of returning an empty config if there is an error. That will just confuse users if there is a typo and will look like a bug. I think returning feedback about these things is important. 

How about the following:
- We do the error checking in the manager, eg in setNewPropDefaults we do the extraction of the user provided module config and return an error if anyting does not work. There is only one user of that function so that would be easy
- We change the signature of m`.moduleConfig.SetSinglePropertyDefaults()` to class `SetSinglePropertyDefaults(*models.Class, prop *models.Property, map[string]interface{})` where the last one is the user module config that can be nil.
- setNewPropDefaults passes the userconfig (if exists), all other users just use nil.

what do you think?

File: usecases/schema/add_property.go [hunk 3]
```diff
@@ -84,9 +87,31 @@ func (m *Manager) addClassProperty(ctx context.Context,
...
 	m.setPropertyDefaults(prop)
+	if err := validateUserProp(class, prop); err != nil {
+		return err
+	}
 	m.moduleConfig.SetSinglePropertyDefaults(class, prop)
+	return nil
+}
+
+func validateUserProp(class *models.Class, prop *models.Property) error {
+	if prop.ModuleConfig != nil {
```
Comment (dirkkul) [inline usecases/schema/add_property.go:100]: return early please eg

```
if prop.ModuleConfig == nil {
    return nil
}
```

File: usecases/schema/add_property.go [hunk 4]
```diff
@@ -84,9 +87,31 @@ func (m *Manager) addClassProperty(ctx context.Context,
...
+		if !ok {
+			return fmt.Errorf("%v property config invalid", prop.Name)
+		}
+		vectorizerConfig, ok := modconfig[class.Vectorizer]
+		if !ok {
+			return fmt.Errorf("%v vectorizer module not part of the property", class.Vectorizer)
+		}
+		_, ok = vectorizerConfig.(map[string]interface{})
+		if !ok {
+			return errors.New("invalid module config")
```
Comment (dirkkul) [inline usecases/schema/add_property.go:111]: I think we can improve this, eg `vectorizerConfig %v not of type map[string]interface{}` or something

File: usecases/schema/add_property.go [hunk 5]
```diff
@@ -45,8 +46,10 @@ func (m *Manager) addClassProperty(ctx context.Context,
 	}
 	prop.Name = lowerCaseFirstLetter(prop.Name)
 
-	m.setNewPropDefaults(class, prop)
-
+	err = m.setNewPropDefaults(class, prop)
+	if err != nil {
+		return err
+	}
```
Comment (dirkkul) [inline usecases/schema/add_property.go:52]: small style suggestion, feel free to ignore

```
	if err = m.setNewPropDefaults(class, prop); err != nil {
		return err
	}
```

**Review by dirkkul — APPROVED** [review]

File: usecases/schema/add_property.go (hunk 3 above)
Comment (shreyanshshah27) [reply usecases/schema/add_property.go:100]: with the current code also if the `prop.ModuleConfig == nil` then it won't enter the if condition and directly return nil. Not sure how this would help. Let me know if I'm missing something.

Comment (dirkkul) [reply usecases/schema/add_property.go:100]: nothing is wrong with how it is currently done, it's more a it's more a coding style issue. :)

"Catching" some cases early and returning reduces the complexity and mental load of understanding what a function does. But this function is so simple that it doesn't really matter, so feel free to ignore if you prefer the current way

Comment (shreyanshshah27) [reply usecases/schema/add_property.go]: Makes sense. No there is nothing like what I prefer. I was just trying to check if there is anything that I missed.

File: usecases/schema/add_property.go (hunk 5 above)
Comment (shreyanshshah27) [reply usecases/schema/add_property.go:51]: Fixed.

File: usecases/schema/add_property.go (hunk 4 above)
Comment (shreyanshshah27) [reply usecases/schema/add_property.go]: Fixed.

File: usecases/schema/add_property.go (hunk 3 above)
Comment (dirkkul) [reply usecases/schema/add_property.go]: I'm a huge fan of [keep code left](https://gist.github.com/ZacharyRSmith/343962433a89ef1b454a/) and really think it improves things. But ofc everybody has different opinions :)
