### PR TITLE
Prevent Schema Deadlock: Split IncomingCommit into locked/unlocked parts

### LINKED ISSUE #4312: Concurrent schema operations can lead to deadlock
### 3-node cluster
Spin up a 3-node cluster with this `docker-compose.yml`:
```yaml
version: '3.4'
services:
  weaviate-0:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.10
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: '25'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: weaviate-0
      CLUSTER_JOIN: weaviate-0,weaviate-1,weaviate-2
  weaviate-1:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.10
    ports:
    - 8081:8080
    - 50052:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: '25'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: weaviate-1
      CLUSTER_JOIN: weaviate-0,weaviate-1,weaviate-2
  weaviate-2:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.10
    ports:
    - 8082:8080
    - 50053:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: '25'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: weaviate-2
      CLUSTER_JOIN: weaviate-0,weaviate-1,weaviate-2

```

You can spin it up like so:

```sh
docker compose -f docker-compos.yml down --remove-orphans
for i in {0..2}; do docker compose -f docker-compose.yml up -d weaviate-$i; sleep 5; done
```

### A chaotic script

Run the following script to induce chaos in the cluster:
```python
import multiprocessing
import weaviate
import weaviate.classes as wvc
import random, string
import warnings
import numpy as np
import time

warnings.filterwarnings("ignore", category=ResourceWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)


num_servers = 3


def run(worker_id: int):
    # send all the class delete/create to the same node
    client = weaviate.connect_to_local(port=8080, grpc_port=50051)
    client = weaviate.connect_to_local()
    client.collections.delete_all()
    client.collections.create(
        "MT",
        multi_tenancy_config=wvc.config.Configure.multi_tenancy(enabled=True),
        vector_index_config=wvc.config.Configure.VectorIndex.flat(),
    )
    client.close()

    # send all the tenant operations to any node
    port = 8080 + worker_id % num_servers
    grpc_port = 50051 + worker_id % num_servers

    client = weaviate.connect_to_local(port=port, grpc_port=grpc_port)

    tenants = [
        wvc.tenants.Tenant(
            name=f"t_{''.join(random.choices(string.ascii_lowercase, k=10))}"
        )
        for i in range(50)
    ]

    try:
        col = client.collections.get("MT")
        start = time.time()
        col.tenants.create(tenants)
        took = time.time() - start
        print(f"created tenant batch in {took:.2f}")

        with client.batch.fixed_size(50, 4) as batch:
            for tenant in tenants:
                for j in range(10):
                    batch.add_object(
                        "MT",
                        vector=np.random.rand(1, 1536)[0].tolist(),
                        tenant=tenant,
                    )
        failed = client.batch.failed_objects
        if len(failed) > 0:
            print(f"have {len(failed)} failures")
    except Exception as e:
        print(f"Error: {e}")
        # if "concurrent" in str(e):
        #     time.sleep(0.1)


def run_in_parallel():
    args = range(50)

    with multiprocessing.Pool() as pool:
        results = pool.map(run, args)


if __name__ == "__main__":
    run_in_parallel()
```

### What is the expected behavior?

It is completely expected that the chaos script shows lots of errors, it does operations that aren't compatible (such as deleting a class while adding tenants into that same class from another thread. However, what we don't expect to see is nodes dead-locking. I should be able to query e.g. the schema-status endpoint just fine:

```
for port in {8080..8082}; do curl -m 3 localhost:$port/v1/schema/cluster-status; done
{"healthy":true,"hostname":"weaviate-0","ignoreSchemaSync":false,"nodeCount":3}
{"healthy":true,"hostname":"weaviate-1","ignoreSchemaSync":false,"nodeCount":3}
{"healthy":true,"hostname":"weaviate-2","ignoreSchemaSync":false,"nodeCount":3}
```

### What is the actual behavior?

```
for port in {8080..8082}; do curl -m 3 localhost:$port/v1/schema/cluster-status; done
curl: (28) Operation timed out after 3002 milliseconds with 0 bytes received
curl: (28) Operation timed out after 3005 milliseconds with 0 bytes received
curl: (28) Operation timed out after 3003 milliseconds with 0 bytes received
```

At least two of three, often all three nodes, time out to schema requests. Note that my initial analysis showed that typically only one node is actually dead-locked. The rest is just cascading failures because the nodes try to contact the deadlocked node which can't respond.

### Supporting information

_No response_

### Server Version

`v1.23.10`, should affect all recent versions from at least `v1.19` on

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

### PR DESCRIPTION
**Pull request by etiennedi**
### What's being changed:
- Split `TxManager.IncomingCommitTransaction` into three parts
- Previously, it would hold the `TxManager.Lock()` for the entire duration
- However, that lock is only designed to protect against accessing `.currentTransaction`
- It is not needed for mutual exclusion of running Commit operations. They are already mutually exclusive because there can only be one Tx at a time
- This lead to a circular kind of deadlock as described in #4312 because the TxManager might be waiting for the SchemaManager which is in turn waiting for the TxManager under concurrent load
- The fix now only holds the lock while accessing variables that need to be protected, but no longer holds the lock while running the `commitFn` which in turn locks the SchemaManager
- fixes #4312 

### Notes
The entire tx logic (and therefore both the bug and this fix) will go away with #4280 (to be released in `v1.25`), however, we cannot predict what update journeys are going to be like, so a fix for old versions will still come in very handy.

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline: not yet - will do
- [x] All new code is covered by tests where it is reasonable: Tested through the [multi-tenancy-loadtest](https://github.com/weaviate/multi-tenancy-load-test/issues/3) where it was first discovered. Another manual way to validate this is outlined in #4312.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by etiennedi** [comment]
This PR is aimed at `stable/v1.23`. If accepted, we should at least release this as `1.23.x` and `1.24.x`, but we might also consider back-porting this to `1.22.x`.

File: usecases/cluster/transactions_write.go [hunk 1]
```diff
@@ -466,32 +466,69 @@ func (c *TxManager) IncomingCommitTransaction(ctx context.Context,
...
 	defer c.ongoingCommits.Done()
 
+	// requires locking because it accesses c.currentTransaction
+	txCopy, err := c.incomingCommitTxValidate(ctx, tx)
+	if err != nil {
+		return err
+	}
+
+	// cannot use locking because of risk of deadlock, see comment inside method
+	if err := c.incomingTxCommitApplyCommitFn(ctx, txCopy); err != nil {
```
Comment (reyreaud-l) [inline usecases/cluster/transactions_write.go:476]: We don't update txCopy with thre returned value from `incomingTxCommitApplyCommitFn`, which mean we then use the original tx for cleanup instead of the updated one. Not sure if critical but as we are doing it between `incomingCommitTxValidate` and `incomingTxCommitApplyCommitFn` maybe it makes sense to keep doing it ?

Comment (etiennedi) [reply usecases/cluster/transactions_write.go:476]: The cleanup is purely ID-based (it sets the `.currentTransaction` to `nil` and deletes by id from the store). So I _think_ it should have no real impact. Maybe to make that clear it would be cleaner to not pass the whole tx, but only the ID?

Comment (reyreaud-l) [reply usecases/cluster/transactions_write.go:476]: If it's using only the ID then it should be OK I think.

**Review by parkerduckworth — APPROVED** [review]

**Review by reyreaud-l — APPROVED** [review]
