### PR TITLE
Fix vectorization of concepts in nearText argument

### LINKED ISSUE #3187: Fix query result vector in all vectorizer modules
For consistency of `nearText` calculated embedding, we need to first get a vector for each passed concept and then calculate combined vector, so that result vector would be always the same no matter the order of concepts.

### PR DESCRIPTION
**Pull request by antas-marcin**
### What's being changed:

This fixes how we create vector using `nearText` argument when there are passed multiple `concepts`.
This PR closes #3187 issue.
 
### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

File: modules/text2vec-cohere/ent/vectorization_result.go [hunk 1]
```diff
@@ -14,5 +14,5 @@ package ent
 type VectorizationResult struct {
 	Text       []string
 	Dimensions int
-	Vector     []float32
+	Vector     [][]float32
```
Comment (aliszka) [inline modules/text2vec-cohere/ent/vectorization_result.go:17]: can it be renamed to `Vectors`?

File: modules/text2vec-cohere/vectorizer/objects.go [hunk 2]
```diff
@@ -138,7 +138,11 @@ func (v *Vectorizer) object(ctx context.Context, className string,
 		return nil, err
 	}
 
-	return res.Vector, nil
+	if len(res.Vector) > 1 {
+		return v.CombineVectors(res.Vector), nil
+	}
+
+	return res.Vector[0], nil
```
Comment (aliszka) [inline modules/text2vec-cohere/vectorizer/objects.go:145]: should `res.Vector` be checked to have at least one vector?

File: modules/text2vec-palm/ent/vectorization_result.go [hunk 3]
```diff
@@ -12,7 +12,7 @@
 package ent
 
 type VectorizationResult struct {
-	Text       string
+	Text       []string
```
Comment (aliszka) [inline modules/text2vec-palm/ent/vectorization_result.go:15]: can it be renamed to `Texts`?

File: modules/text2vec-palm/ent/vectorization_result.go [hunk 4]
```diff
@@ -12,7 +12,7 @@
...
 	Dimensions int
-	Vector     []float32
+	Vector     [][]float32
```
Comment (aliszka) [inline modules/text2vec-palm/ent/vectorization_result.go:17]: can it be renamed to `Vectors`?

File: modules/text2vec-palm/vectorizer/objects.go [hunk 5]
```diff
@@ -141,7 +141,11 @@ func (v *Vectorizer) object(ctx context.Context, className string,
 		return nil, err
 	}
 
-	return res.Vector, nil
+	if len(res.Vector) > 1 {
+		return v.CombineVectors(res.Vector), nil
+	}
+
+	return res.Vector[0], nil
```
Comment (aliszka) [inline modules/text2vec-palm/vectorizer/objects.go:148]: check for `len(res.Vector) == 1` ?

**Review by aliszka — DISMISSED** [review]

File: modules/text2vec-cohere/ent/vectorization_result.go (hunk 1 above)
Comment (antas-marcin) [reply modules/text2vec-cohere/ent/vectorization_result.go]: fixed

File: modules/text2vec-cohere/vectorizer/objects.go (hunk 2 above)
Comment (antas-marcin) [reply modules/text2vec-cohere/vectorizer/objects.go]: Added a check. Thanks

File: modules/text2vec-palm/ent/vectorization_result.go (hunk 3 above)
Comment (antas-marcin) [reply modules/text2vec-palm/ent/vectorization_result.go]: done

File: modules/text2vec-palm/ent/vectorization_result.go (hunk 4 above)
Comment (antas-marcin) [reply modules/text2vec-palm/ent/vectorization_result.go]: done

File: modules/text2vec-palm/vectorizer/objects.go (hunk 5 above)
Comment (antas-marcin) [reply modules/text2vec-palm/vectorizer/objects.go]: Added a check. Thanks

**Review by aliszka — APPROVED** [review]
