### PR TITLE
Fix: PQ recall not identical after restart; in condensor replay PQ information into new log if present

### LINKED ISSUE #3048: Bug: PQ information lost after restart
The condensor removes PQ-related info from the commit log.

Reproduce:
1. Import SIFT1M
2. Restart
3. Update schema (triggers re-compression).

### PR DESCRIPTION
**Pull request by etiennedi**
### What's being changed:
* The condensor takes individual HNSW commit logs and removes redundancies
* Before this fix if the original commit log contained PQ information, that information was lost in the condensed output
* This fix takes the information that was written in the original and rewrites it into the new log
* A new test was added to prove that this works. Note: For simplicity's sake, `M` was set to `0`, which means the test only contains metadata, no actual encoder data. This means the test might only tests part of the information we want to retain. The test could probably be improved by writing meaningful data, but for this I need help from @abdelr or @trengrj 
* Note that there is a possibly related bug #3049 which is not fixed in this PR. Note that #3049 also occurs if the condenser is turned off completely, so I believe it has another cause
* fixes #3048 

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [x] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by trengrj** [comment]
I added sample encoder data to the test. @abdelr when you are back would be great if you could review.

**Comment by abdelr** [comment]
Hey, I think the fix is correct. I wonder why in general we have copied the methods from the Logger to the Condenser though. Could we not easily break something in the future? I do notice that they both have their own buffer but maybe we could have some generic functions to AddNode, AddPQ... that receives the buffer and then use these functions from the Logger and the Condenser. But maybe this comment goes beyond this PR.

File: adapters/repos/db/vector/hnsw/condensor.go [hunk 1]
```diff
@@ -228,6 +235,27 @@ func (c *MemoryCondensor) AddTombstone(nodeid uint64) error {
 	return ec.ToError()
 }
 
+func (c *MemoryCondensor) AddPQ(data ssdhelpers.PQData) error {
```
Comment (abdelr) [inline adapters/repos/db/vector/hnsw/condensor.go:238]: We have a similar method in weaviate/adapters/repos/db/vector/hnsw/commitlog/logger.go. I do notice they both (Logger and Condensor) have independent buffers (toWrite) but we could still have a helper function receiving the buffers and doing the duplicated work. This way we avoid potential bugs in the future when changing the code. Maybe the comment goes beyond the PR since we also have a similar situation for example for AddNode method (not new in the PR).

**Review by abdelr — APPROVED** [review]
Maybe we could just open an issue for the comment I wrote and address it later so I have just marked the PR ready as to merge
